### ISSUE TITLE
no statistics Data

### ISSUE THREAD

**Issue by d1etmar** [shivan/homeassistant-liquidcheck#14]
Hello,

It seems there is a problem with the sensor that it does not get picked up by the recorder for statistics long term data . I do not see them in the Developer Tools statistics page. If i check the state it misses a device_class field if i compare to other entities .

This shows up in the State : sensor.<ip>.Inhalt

unit_of_measurement: L
icon: ""
friendly_name: 192.168.xxx.xxx Inhalt

Or do i have some other problem ? 

I am using Version 1.0.4 , and HA 2025.5.1

The sensor is great. I like it a lot .

Best regards, Dietmar

**Comment by shivan** [comment]
Do you mean other statistics than these, or exactly these:

![Image](https://github.com/user-attachments/assets/1625191d-854a-4bfd-9a21-26a0c8f99a15)

?

**Comment by d1etmar** [comment]
Hi , i might be wrong. But i have only the short term history for the "Inhalt" Entity .  As said i do not have the "Inhalt" entity under Developement Statistics ( long term )  . I read/searched  that there is a need that registered entities need to have a state_class  / device_class or similar to be picked up by long term statistics . So this is only a very not knowing guess , as i am a very nyb on home automation / hA ...

thx for your fast answer ! . All other stuff is great .

Br, Dietmar

**Comment by d1etmar** [comment]
Hi, It would be great to know if soneone has longer history Data than the default 14 days by the recorder. for the  Inhalt and % Full entity  . I real want to have long history and if the problem is on my side i am happy to try to fix it "somehow" by myself ....

or if they see under Developement Tools - Statistics the Inhalt entity ... which would help a lot to try to fix it for me :) ...

Thx, Dietmar

upd: 

this fixxed it for me in the configuration.yaml

homeassistant:
   customize:
     sensor.192_168_199_156_inhalt: 
       state_class: measurement

**Comment by Phoenix-DH** [comment]
Does that mean that you will have no statistics for longer than 10 days or so?
I just checked mine and also other sensors, it is the same, no long term.

Would also love to see a fix here.

I do not know @shivan how much work that is, because I have no python skills. Thanks. Or can we support in some way?

**Comment by d1etmar** [comment]
Hi,

As i am so happy about the lovely sensor i share my stuff i made during the last days .

This is an sample Apex Chart for this Sensor with some custom arround, but to get the idea

![Image](https://github.com/user-attachments/assets/372abe3d-7a26-4dd4-813d-3fdad490a539)

This is the yaml code for it, it adds a rain sensor and shows the usable/pullable Water in L only ( it reduces it by 550 L because the pump could not get all ) . ( it is the transform : return x - 550 ) . I just made a new sensor yesterday which just substract the Inhalt entity for the amount which cannot be pulled by the pump .

The hole Idea is to show much much rain it needs to fill up the Zisterne . Also how much was used in the Past .

````
type: custom:stack-in-card
title: null
mode: vertical
card_mod:
  style: |
    ha-card { border: none; box-shadow: none; }  
cards:
  - type: custom:stack-in-card
    mode: horizontal
    card_mod:
      style: |
        ha-card { border: none; box-shadow: none; }      
    cards:
      - type: entities
        card_mod:
          style: |
            ha-card { border: none; box-shadow: none; }  
        entities:
          - entity: sensor.192_168_199_156_fullstand
            name: Füllstand
        title: Zisterne
  - type: custom:apexcharts-card
    header:
      show: true
      show_states: true
      colorize_states: true
    update_interval: 30m
    span:
      end: day
    graph_span: 10days
    show:
      loading: true
    yaxis:
      - id: first
        decimals: 0
        min: 0
        max: 6000
      - id: second
        opposite: true
        min: 0
        decimals: 0
        max: 40
    apex_config:
      dataLabels:
        enabled: true
        textAnchor: start
      tooltip:
        enabled: true
        enabledOnSeries: undefinded
        shared: Boolean
      chart:
        height: 200px
      grid:
        show: true
        strokeDashArray: 0
        borderColor: "#444444"
        position: back
        xaxis:
          lines:
            show: true
        yaxis:
          lines:
            show: true
      xaxis:
        tooltip:
          enabled: false
        type: datetime
        axisTicks:
          show: true
        labels:
          format: dd-MMM
        lines:
          show: true
    series:
      - entity: sensor.gw2000a_daily_rain
        color: green
        name: Regen
        type: area
        yaxis_id: second
        opacity: 0.7
        invert: false
        stroke_width: 2
        offset: "-0d"
        extend_to: false
        group_by:
          func: last
          duration: 1day
          fill: last
        show:
          datalabels: true
          in_header: true
          in_legend: false
          legend_value: true
          in_chart: true
          offset_in_name: false
      - entity: sensor.192_168_199_156_inhalt
        transform: return x - 550
        color: blue
        name: Zisterne
        opacity: 0.5
        type: column
        invert: false
        stroke_width: 1
        yaxis_id: first
        offset: "-0d"
        extend_to: now
        group_by:
          func: last
          duration: 1day
          fill: last
        show:
          datalabels: false
          in_header: true
          in_legend: false
          legend_value: true
          in_chart: true
          offset_in_name: false
      - entity: sensor.192_168_199_156_inhalt
        transform: return x - 550
        color: blue
        name: Max
        type: line
        invert: false
        stroke_width: 2
        yaxis_id: first
        offset: "-0d"
        extend_to: now
        group_by:
          func: max
          duration: 1day
          fill: last
        show:
          datalabels: false
          in_header: true
          in_legend: false
          legend_value: true
          in_chart: true
          offset_in_name: false
      - entity: sensor.192_168_199_156_inhalt
        transform: return x - 550
        color: red
        name: Min
        type: line
        invert: false
        stroke_width: 1
        yaxis_id: first
        offset: "-0d"
        extend_to: now
        group_by:
          func: min
          duration: 1day
          fill: last
        show:
          datalabels: false
          in_header: true
          in_legend: false
          legend_value: true
          in_chart: true
          offset_in_name: false
    all_series_config:
      stroke_width: 2
      type: line

````

I also made some templates to show the Daily changes for this sensor ( Zugang / Abgang ) 

![Image](https://github.com/user-attachments/assets/d36b7c73-c446-4cf3-a621-e33f98f12e8b)


this is the complete zisterne.yaml i made for it ( actually a chatgpt ... quite good results btw ! )

```

# water_tracker.yaml

input_number:
  water_last_value:
    name: Water Last Value
    min: 0
    max: 10000
    step: 1
    mode: box

  water_gain:
    name: Water Gain Today
    min: 0
    max: 10000
    step: 1
    mode: box

  water_loss:
    name: Water Loss Today
    min: 0
    max: 10000
    step: 1
    mode: box

automation:
  - alias: Track Water Reservoir Changes
    description: Track water gain/loss based on reservoir level changes
    trigger:
      - platform: state
        entity_id: sensor.192_168_199_156_inhalt
    condition:
      - condition: template
        value_template: >
            {% set sensor_value = states('sensor.192_168_199_156_inhalt') | float(0) %}
            {% set last_value = states('input_number.water_last_value') | float(0) %}
            {{ sensor_value > 0 and sensor_value != last_value }}
    action:
      - variables:
          current: "{{ states('sensor.192_168_199_156_inhalt') | float(0) }}"
          last: "{{ states('input_number.water_last_value') | float(0) }}"
          delta: "{{ current - last }}"
      - choose:
          - conditions: "{{ delta > 0 }}"
            sequence:
              - service: input_number.set_value
                data:
                  entity_id: input_number.water_gain
                  value: >
                    {{ states('input_number.water_gain') | float + delta }}
          - conditions: "{{ delta < 0 }}"
            sequence:
              - service: input_number.set_value
                data:
                  entity_id: input_number.water_loss
                  value: >
                    {{ states('input_number.water_loss') | float + (-delta) }}
      - service: input_number.set_value
        data:
          entity_id: input_number.water_last_value
          value: "{{ current }}"
    mode: queued

  - alias: Reset Daily Water Gain and Loss
    description: Resets daily water gain and loss values at midnight
    trigger:
      - platform: time
        at: '00:00:00'
    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.water_gain
          value: 0
      - service: input_number.set_value
        data:
          entity_id: input_number.water_loss
          value: 0

template:
  - sensor:
      - name: "Inhalt Netto"
        unique_id: inhalt_netto
        unit_of_measurement: "L" 
        state_class: measurement
        state: >
          {% set original = states('sensor.192_168_199_156_inhalt') | float(0) %}
          {{ original - 550 }}


```

for the long term Statistics : add to the configuration.yaml under homeassistant / customize: your sensor entity.

```
homeassistant:
  packages: !include_dir_named integrations
  customize:
    sensor.192_168_199_156_inhalt: 
      state_class: measurement 
```

have fun.

Dietmar

**Comment by d1etmar** [comment]
Hi,

I improved it a bit with better nice Tooltip showing ( remove the min and max values, icons adapt header .... )

<img width="1080" height="675" alt="Image" src="https://github.com/user-attachments/assets/f81d07c5-9206-4903-94d8-708aa04136d8" />

````
type: custom:stack-in-card
title: null
mode: vertical
card_mod:
  style: |
    ha-card { border: none; box-shadow: none; }  
cards:
  - type: custom:stack-in-card
    mode: horizontal
    card_mod:
      style: |
        ha-card { border: none; box-shadow: none; }      
    cards:
      - type: entities
        card_mod:
          style: |
            ha-card { border: none; box-shadow: none; }  
        entities:
          - entity: sensor.inhalt_netto
            type: custom:multiple-entity-row
            name: Zisterne
            secondary_info: last-changed
            show_state: false
            tap_action:
              action: call-service
              service: script.start_zisterne_measurement
            entities:
              - entity: sensor.inhalt_netto
                name: Inhalt
                tap_action:
                  action: call-service
                  service: script.start_zisterne_measurement
              - entity: input_number.water_gain
                name: Zugang
              - entity: input_number.water_loss
                name: Abgang
  - type: custom:apexcharts-card
    card_mod:
      style: |
        .apexcharts-marker,
         .apexcharts-tooltip-marker {
            display: none !important;
         }        
        ha-card { border: none; box-shadow: none; }      
    header:
      show: true
      show_states: true
      colorize_states: true
    update_interval: 30m
    graph_span: 10days
    span:
      end: day
    show:
      loading: true
    yaxis:
      - id: first
        decimals: 0
        min: 0
        max: 6000
      - id: second
        opposite: true
        min: 0
        decimals: 0
        max: 40
    apex_config:
      dataLabels:
        enabled: true
        textAnchor: start
      tooltip:
        shared: true
        intersect: false
        x:
          format: dd-MMM
          show: true
        "y":
          formatter: |
            EVAL: function(val1, { series, seriesIndex, dataPointIndex }) {
              return `${series[0][dataPointIndex].toFixed(2)} L Regen<br>` +
                     `${series[1][dataPointIndex].toFixed(2)} L Zisterne<br>` ;
                     
            }
          title:
            formatter: |
              EVAL: function(seriesName) {
                return ""
              }
      chart:
        height: 200px
      grid:
        show: true
        strokeDashArray: 0
        borderColor: "#444444"
        position: back
        xaxis:
          lines:
            show: true
        yaxis:
          lines:
            show: true
      xaxis:
        tooltip:
          enabled: false
        type: datetime
        axisTicks:
          show: true
        labels:
          format: dd-MMM
        lines:
          show: true
    series:
      - entity: sensor.gw2000a_daily_rain
        color: green
        name: Regen
        type: area
        yaxis_id: second
        opacity: 0.7
        invert: false
        stroke_width: 2
        offset: "-0d"
        extend_to: false
        group_by:
          func: max
          duration: 1day
          fill: last
        show:
          datalabels: true
          in_header: false
          in_legend: true
          legend_value: false
          in_chart: true
          offset_in_name: false
      - entity: sensor.192_168_199_156_inhalt
        transform: return x - 550
        color: blue
        name: Zisterne
        opacity: 0.5
        type: column
        invert: false
        stroke_width: 1
        yaxis_id: first
        offset: "-0d"
        extend_to: now
        group_by:
          func: last
          duration: 1day
          fill: last
        show:
          datalabels: false
          in_header: false
          in_legend: true
          legend_value: false
          in_chart: true
          offset_in_name: false
      - entity: sensor.192_168_199_156_inhalt
        transform: return x - 550
        color: orange
        name: Max
        type: line
        invert: false
        stroke_width: 2
        yaxis_id: first
        offset: "-0d"
        extend_to: now
        group_by:
          func: max
          duration: 24hours
          fill: last
        show:
          datalabels: false
          in_header: false
          in_legend: true
          legend_value: false
          in_chart: true
          offset_in_name: false
      - entity: sensor.192_168_199_156_inhalt
        transform: return x - 550
        color: red
        name: Min
        type: line
        invert: false
        stroke_width: 1
        yaxis_id: first
        offset: "-0d"
        extend_to: now
        group_by:
          func: min
          duration: 1day
          fill: last
        show:
          datalabels: false
          in_header: false
          in_legend: true
          legend_value: false
          in_chart: true
          offset_in_name: false
    all_series_config:
      stroke_width: 2
      type: line

````
