### ISSUE TITLE
Ability to trigger a new measurement

### ISSUE THREAD

**Issue by cdickmann** [shivan/homeassistant-liquidcheck#2]
It would be great to also have an action to trigger the measurement. Is this something you plan to add? Or would you accept/prefer a PR?

**Comment by shivan** [comment]
I would accept PRs, but first I want to finish my change for integrating it officially into hacs.

**Comment by Phoenix-DH** [comment]
@shivan 
Is this already implemented?

I found some code:
```
rest_command:
  messung_zisterne:
    url: http://192.168.178.122/command
    method: POST
    payload: '{ "header" : { "namespace" : "Device.Control" , "name" : "StartMeasure" , "messageId" : "1" , "payloadVersion" : "1" } , "payload" : null }' 
    content_type: 'application/json; charset=utf-8'
```
    
Is the update cycle of the build-in updste adjustable? I found somewhere that it gets updated every 30 seconds. Is that not too much?
